//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaEntities1 : DbContext
    {
        public CinemaEntities1()
            : base("name=CinemaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChipInfo> ChipInfo { get; set; }
        public virtual DbSet<CinemaInfo> CinemaInfo { get; set; }
        public virtual DbSet<CommentInfo> CommentInfo { get; set; }
        public virtual DbSet<MovieInfo> MovieInfo { get; set; }
        public virtual DbSet<MusicInfo> MusicInfo { get; set; }
        public virtual DbSet<NewsInfo> NewsInfo { get; set; }
        public virtual DbSet<OfficeInfo> OfficeInfo { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<SeatInfo> SeatInfo { get; set; }
        public virtual DbSet<UsersInfo> UsersInfo { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<OrdersGoodsInfo> OrdersGoodsInfo { get; set; }
        public virtual DbSet<UrlCountInnfo> UrlCountInnfo { get; set; }
    }
}
