//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieInfo()
        {
            this.CommentInfo = new HashSet<CommentInfo>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string MovieCover { get; set; }
        public string MovieBrief { get; set; }
        public decimal MovieMoney { get; set; }
        public System.DateTime MovieReleaseDate { get; set; }
        public int MovieDuration { get; set; }
        public string MovieDirect { get; set; }
        public string MovieType { get; set; }
        public string MovieArea { get; set; }
        public Nullable<int> MovieYears { get; set; }
        public Nullable<decimal> MovieScore { get; set; }
        public string MoviePeople { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentInfo> CommentInfo { get; set; }
    }
}
