//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderID { get; set; }
        public int SeatID { get; set; }
        public decimal OrderDetailsPrice { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime StopTime { get; set; }
        public int PrimaryKey { get; set; }
    
        public virtual OrderInfo OrderInfo { get; set; }
        public virtual SeatInfo SeatInfo { get; set; }
    }
}
