//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersGoodsInfo
    {
        public int CinemaID { get; set; }
        public int OfficeID { get; set; }
        public string MovieName { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime StopTime { get; set; }
    
        public virtual CinemaInfo CinemaInfo { get; set; }
        public virtual OfficeInfo OfficeInfo { get; set; }
    }
}
