//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersInfo()
        {
            this.CommentInfo = new HashSet<CommentInfo>();
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public int UsersID { get; set; }
        public string UserAccount { get; set; }
        public string UsersPwd { get; set; }
        public string UserName { get; set; }
        public string UserSex { get; set; }
        public string UserPhone { get; set; }
        public string UserIDCard { get; set; }
        public string UserAddress { get; set; }
        public Nullable<int> UserLevelNum { get; set; }
        public Nullable<int> UserMvp { get; set; }
        public string UserFace { get; set; }
        public string UserEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentInfo> CommentInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
        public virtual UsersInfo UsersInfo1 { get; set; }
        public virtual UsersInfo UsersInfo2 { get; set; }
    }
}
